# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ingresar.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_fmIngresar(object):
    def setupUi(self, fmIngresar):
        fmIngresar.setObjectName("fmIngresar")
        fmIngresar.resize(460, 385)
        fmIngresar.setMinimumSize(QtCore.QSize(460, 385))
        fmIngresar.setMaximumSize(QtCore.QSize(460, 385))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconos/freeicons24x24/alien.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        fmIngresar.setWindowIcon(icon)
        fmIngresar.setModal(False)
        self.fmeFecha = QtWidgets.QFrame(fmIngresar)
        self.fmeFecha.setGeometry(QtCore.QRect(0, 4, 460, 175))
        self.fmeFecha.setMinimumSize(QtCore.QSize(460, 175))
        self.fmeFecha.setMaximumSize(QtCore.QSize(460, 175))
        self.fmeFecha.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fmeFecha.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmeFecha.setObjectName("fmeFecha")
        self.layoutWidget = QtWidgets.QWidget(self.fmeFecha)
        self.layoutWidget.setGeometry(QtCore.QRect(16, 10, 432, 150))
        self.layoutWidget.setObjectName("layoutWidget")
        self.glFecha = QtWidgets.QGridLayout(self.layoutWidget)
        self.glFecha.setContentsMargins(0, 0, 0, 0)
        self.glFecha.setObjectName("glFecha")
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.layoutWidget)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.glFecha.addWidget(self.timeEdit_2, 0, 3, 1, 1)
        self.lblcPas_2 = QtWidgets.QLabel(self.layoutWidget)
        self.lblcPas_2.setObjectName("lblcPas_2")
        self.glFecha.addWidget(self.lblcPas_2, 3, 0, 1, 1)
        self.lblfIngreso = QtWidgets.QLabel(self.layoutWidget)
        self.lblfIngreso.setObjectName("lblfIngreso")
        self.glFecha.addWidget(self.lblfIngreso, 0, 0, 1, 1)
        self.lblhIngreso = QtWidgets.QLabel(self.layoutWidget)
        self.lblhIngreso.setObjectName("lblhIngreso")
        self.glFecha.addWidget(self.lblhIngreso, 0, 2, 1, 1)
        self.dtefIngreso = QtWidgets.QDateEdit(self.layoutWidget)
        self.dtefIngreso.setObjectName("dtefIngreso")
        self.glFecha.addWidget(self.dtefIngreso, 0, 1, 1, 1)
        self.lblhEgreso = QtWidgets.QLabel(self.layoutWidget)
        self.lblhEgreso.setObjectName("lblhEgreso")
        self.glFecha.addWidget(self.lblhEgreso, 1, 2, 1, 1)
        self.lblfEgreso = QtWidgets.QLabel(self.layoutWidget)
        self.lblfEgreso.setObjectName("lblfEgreso")
        self.glFecha.addWidget(self.lblfEgreso, 1, 0, 1, 1)
        self.lblcPas = QtWidgets.QLabel(self.layoutWidget)
        self.lblcPas.setObjectName("lblcPas")
        self.glFecha.addWidget(self.lblcPas, 2, 2, 1, 1)
        self.lblnHab = QtWidgets.QLabel(self.layoutWidget)
        self.lblnHab.setObjectName("lblnHab")
        self.glFecha.addWidget(self.lblnHab, 2, 0, 1, 1)
        self.cbocPas = QtWidgets.QComboBox(self.layoutWidget)
        self.cbocPas.setObjectName("cbocPas")
        self.cbocPas.addItem("")
        self.cbocPas.addItem("")
        self.cbocPas.addItem("")
        self.cbocPas.addItem("")
        self.glFecha.addWidget(self.cbocPas, 2, 3, 1, 1)
        self.timeEdit = QtWidgets.QTimeEdit(self.layoutWidget)
        self.timeEdit.setObjectName("timeEdit")
        self.glFecha.addWidget(self.timeEdit, 1, 3, 1, 1)
        self.dtefEgreso = QtWidgets.QDateEdit(self.layoutWidget)
        self.dtefEgreso.setObjectName("dtefEgreso")
        self.glFecha.addWidget(self.dtefEgreso, 1, 1, 1, 1)
        self.cbonHab = QtWidgets.QComboBox(self.layoutWidget)
        self.cbonHab.setObjectName("cbonHab")
        self.cbonHab.addItem("")
        self.cbonHab.addItem("")
        self.cbonHab.addItem("")
        self.cbonHab.addItem("")
        self.cbonHab.addItem("")
        self.cbonHab.addItem("")
        self.cbonHab.addItem("")
        self.cbonHab.addItem("")
        self.cbonHab.addItem("")
        self.cbonHab.addItem("")
        self.cbonHab.addItem("")
        self.cbonHab.addItem("")
        self.cbonHab.addItem("")
        self.cbonHab.addItem("")
        self.cbonHab.addItem("")
        self.cbonHab.addItem("")
        self.cbonHab.addItem("")
        self.cbonHab.addItem("")
        self.cbonHab.addItem("")
        self.glFecha.addWidget(self.cbonHab, 2, 1, 1, 1)
        self.txtcPas = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtcPas.setObjectName("txtcPas")
        self.glFecha.addWidget(self.txtcPas, 3, 1, 1, 1)
        self.btnBuscar = QtWidgets.QPushButton(self.layoutWidget)
        self.btnBuscar.setEnabled(True)
        self.btnBuscar.setCheckable(False)
        self.btnBuscar.setDefault(False)
        self.btnBuscar.setFlat(False)
        self.btnBuscar.setObjectName("btnBuscar")
        self.glFecha.addWidget(self.btnBuscar, 3, 2, 1, 2)
        self.fmeDatos = QtWidgets.QFrame(fmIngresar)
        self.fmeDatos.setGeometry(QtCore.QRect(0, 177, 460, 181))
        self.fmeDatos.setMaximumSize(QtCore.QSize(460, 16777215))
        self.fmeDatos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fmeDatos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmeDatos.setObjectName("fmeDatos")
        self.layoutWidget_2 = QtWidgets.QWidget(self.fmeDatos)
        self.layoutWidget_2.setGeometry(QtCore.QRect(17, 11, 431, 164))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.glDatos = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.glDatos.setContentsMargins(0, 0, 0, 0)
        self.glDatos.setObjectName("glDatos")
        self.lblEciv = QtWidgets.QLabel(self.layoutWidget_2)
        self.lblEciv.setObjectName("lblEciv")
        self.glDatos.addWidget(self.lblEciv, 4, 0, 1, 1)
        self.lbl02 = QtWidgets.QLabel(self.layoutWidget_2)
        self.lbl02.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbl02.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl02.setObjectName("lbl02")
        self.glDatos.addWidget(self.lbl02, 1, 1, 1, 1)
        self.lbl04 = QtWidgets.QLabel(self.layoutWidget_2)
        self.lbl04.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbl04.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl04.setObjectName("lbl04")
        self.glDatos.addWidget(self.lbl04, 3, 1, 1, 1)
        self.lbl01 = QtWidgets.QLabel(self.layoutWidget_2)
        self.lbl01.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbl01.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl01.setObjectName("lbl01")
        self.glDatos.addWidget(self.lbl01, 0, 1, 1, 1)
        self.lblNac = QtWidgets.QLabel(self.layoutWidget_2)
        self.lblNac.setObjectName("lblNac")
        self.glDatos.addWidget(self.lblNac, 3, 0, 1, 1)
        self.lbl05 = QtWidgets.QLabel(self.layoutWidget_2)
        self.lbl05.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbl05.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl05.setObjectName("lbl05")
        self.glDatos.addWidget(self.lbl05, 4, 1, 1, 1)
        self.lblAyN = QtWidgets.QLabel(self.layoutWidget_2)
        self.lblAyN.setObjectName("lblAyN")
        self.glDatos.addWidget(self.lblAyN, 0, 0, 1, 1)
        self.lbl03 = QtWidgets.QLabel(self.layoutWidget_2)
        self.lbl03.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbl03.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl03.setObjectName("lbl03")
        self.glDatos.addWidget(self.lbl03, 2, 1, 1, 1)
        self.lblNdoc = QtWidgets.QLabel(self.layoutWidget_2)
        self.lblNdoc.setObjectName("lblNdoc")
        self.glDatos.addWidget(self.lblNdoc, 1, 0, 1, 1)
        self.lbl06 = QtWidgets.QLabel(self.layoutWidget_2)
        self.lbl06.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbl06.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl06.setObjectName("lbl06")
        self.glDatos.addWidget(self.lbl06, 5, 1, 1, 1)
        self.lblOcup = QtWidgets.QLabel(self.layoutWidget_2)
        self.lblOcup.setObjectName("lblOcup")
        self.glDatos.addWidget(self.lblOcup, 2, 0, 1, 1)
        self.lblObs = QtWidgets.QLabel(self.layoutWidget_2)
        self.lblObs.setObjectName("lblObs")
        self.glDatos.addWidget(self.lblObs, 5, 0, 1, 1)
        self.btnIngresar = QtWidgets.QDialogButtonBox(fmIngresar)
        self.btnIngresar.setGeometry(QtCore.QRect(126, 360, 204, 26))
        self.btnIngresar.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnIngresar.setCenterButtons(True)
        self.btnIngresar.setObjectName("btnIngresar")

        self.retranslateUi(fmIngresar)
        self.btnIngresar.rejected.connect(fmIngresar.reject)
        self.btnIngresar.accepted.connect(fmIngresar.accept)
        self.btnBuscar.clicked.connect(fmIngresar.buscar)
        self.txtcPas.textChanged['QString'].connect(self.lbl01.clear)
        self.txtcPas.textChanged['QString'].connect(self.lbl02.clear)
        self.txtcPas.textChanged['QString'].connect(self.lbl03.clear)
        self.txtcPas.textChanged['QString'].connect(self.lbl04.clear)
        self.txtcPas.textChanged['QString'].connect(self.lbl05.clear)
        self.txtcPas.textChanged['QString'].connect(self.lbl06.clear)
        QtCore.QMetaObject.connectSlotsByName(fmIngresar)

    def retranslateUi(self, fmIngresar):
        _translate = QtCore.QCoreApplication.translate
        fmIngresar.setWindowTitle(_translate("fmIngresar", "Ingresar Pasajero"))
        self.lblcPas_2.setText(_translate("fmIngresar", "Codigo Pasajero"))
        self.lblfIngreso.setText(_translate("fmIngresar", "Fecha Ingreso"))
        self.lblhIngreso.setText(_translate("fmIngresar", "Hora de Ingreso"))
        self.lblhEgreso.setText(_translate("fmIngresar", "Hora de Egreso:"))
        self.lblfEgreso.setText(_translate("fmIngresar", "Fecha Egreso"))
        self.lblcPas.setText(_translate("fmIngresar", "Cantidad de Pasajeros:"))
        self.lblnHab.setText(_translate("fmIngresar", "N° de Habitacion:"))
        self.cbocPas.setItemText(0, _translate("fmIngresar", "1"))
        self.cbocPas.setItemText(1, _translate("fmIngresar", "2"))
        self.cbocPas.setItemText(2, _translate("fmIngresar", "3"))
        self.cbocPas.setItemText(3, _translate("fmIngresar", "4"))
        self.cbonHab.setItemText(0, _translate("fmIngresar", "1"))
        self.cbonHab.setItemText(1, _translate("fmIngresar", "2"))
        self.cbonHab.setItemText(2, _translate("fmIngresar", "3"))
        self.cbonHab.setItemText(3, _translate("fmIngresar", "4"))
        self.cbonHab.setItemText(4, _translate("fmIngresar", "5"))
        self.cbonHab.setItemText(5, _translate("fmIngresar", "6"))
        self.cbonHab.setItemText(6, _translate("fmIngresar", "7"))
        self.cbonHab.setItemText(7, _translate("fmIngresar", "8"))
        self.cbonHab.setItemText(8, _translate("fmIngresar", "9"))
        self.cbonHab.setItemText(9, _translate("fmIngresar", "10"))
        self.cbonHab.setItemText(10, _translate("fmIngresar", "11"))
        self.cbonHab.setItemText(11, _translate("fmIngresar", "12"))
        self.cbonHab.setItemText(12, _translate("fmIngresar", "13"))
        self.cbonHab.setItemText(13, _translate("fmIngresar", "14"))
        self.cbonHab.setItemText(14, _translate("fmIngresar", "15"))
        self.cbonHab.setItemText(15, _translate("fmIngresar", "16"))
        self.cbonHab.setItemText(16, _translate("fmIngresar", "17"))
        self.cbonHab.setItemText(17, _translate("fmIngresar", "18"))
        self.cbonHab.setItemText(18, _translate("fmIngresar", "19"))
        self.btnBuscar.setText(_translate("fmIngresar", "Buscar"))
        self.lblEciv.setText(_translate("fmIngresar", "Estado Civil:"))
        self.lbl02.setText(_translate("fmIngresar", "TextLabel"))
        self.lbl04.setText(_translate("fmIngresar", "TextLabel"))
        self.lbl01.setText(_translate("fmIngresar", "TextLabel"))
        self.lblNac.setText(_translate("fmIngresar", "Nacionalidad:"))
        self.lbl05.setText(_translate("fmIngresar", "TextLabel"))
        self.lblAyN.setText(_translate("fmIngresar", "Apellido y Nombre:"))
        self.lbl03.setText(_translate("fmIngresar", "TextLabel"))
        self.lblNdoc.setText(_translate("fmIngresar", "Tipo y N° de Documento:"))
        self.lbl06.setText(_translate("fmIngresar", "TextLabel"))
        self.lblOcup.setText(_translate("fmIngresar", "Ocupacion:"))
        self.lblObs.setText(_translate("fmIngresar", "Observaciones:"))

from . import iconosQ
