# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ListadePrecios.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_listaPrecios(object):
    def setupUi(self, listaPrecios):
        listaPrecios.setObjectName("listaPrecios")
        listaPrecios.resize(716, 600)
        self.centralwidget = QtWidgets.QWidget(listaPrecios)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.fmAgregar = QtWidgets.QFrame(self.centralwidget)
        self.fmAgregar.setEnabled(True)
        self.fmAgregar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fmAgregar.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.fmAgregar.setObjectName("fmAgregar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fmAgregar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblrubro = QtWidgets.QLabel(self.fmAgregar)
        self.lblrubro.setObjectName("lblrubro")
        self.verticalLayout.addWidget(self.lblrubro)
        self.txtrubro = QtWidgets.QLineEdit(self.fmAgregar)
        self.txtrubro.setMinimumSize(QtCore.QSize(140, 0))
        self.txtrubro.setMaximumSize(QtCore.QSize(140, 16777215))
        self.txtrubro.setObjectName("txtrubro")
        self.verticalLayout.addWidget(self.txtrubro)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblarticulo = QtWidgets.QLabel(self.fmAgregar)
        self.lblarticulo.setObjectName("lblarticulo")
        self.verticalLayout_2.addWidget(self.lblarticulo)
        self.txtarticulo = QtWidgets.QLineEdit(self.fmAgregar)
        self.txtarticulo.setMinimumSize(QtCore.QSize(200, 0))
        self.txtarticulo.setMaximumSize(QtCore.QSize(200, 16777215))
        self.txtarticulo.setObjectName("txtarticulo")
        self.verticalLayout_2.addWidget(self.txtarticulo)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblstock = QtWidgets.QLabel(self.fmAgregar)
        self.lblstock.setObjectName("lblstock")
        self.verticalLayout_3.addWidget(self.lblstock)
        self.sbstock = QtWidgets.QSpinBox(self.fmAgregar)
        self.sbstock.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.sbstock.setMaximum(5000)
        self.sbstock.setObjectName("sbstock")
        self.verticalLayout_3.addWidget(self.sbstock)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblprecio = QtWidgets.QLabel(self.fmAgregar)
        self.lblprecio.setAlignment(QtCore.Qt.AlignCenter)
        self.lblprecio.setObjectName("lblprecio")
        self.verticalLayout_4.addWidget(self.lblprecio)
        self.txtprecio = QtWidgets.QLineEdit(self.fmAgregar)
        self.txtprecio.setMinimumSize(QtCore.QSize(70, 0))
        self.txtprecio.setMaximumSize(QtCore.QSize(70, 16777215))
        self.txtprecio.setObjectName("txtprecio")
        self.verticalLayout_4.addWidget(self.txtprecio)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lbdescripcion = QtWidgets.QLabel(self.fmAgregar)
        self.lbdescripcion.setObjectName("lbdescripcion")
        self.verticalLayout_5.addWidget(self.lbdescripcion)
        self.txtdescripcion = QtWidgets.QLineEdit(self.fmAgregar)
        self.txtdescripcion.setObjectName("txtdescripcion")
        self.verticalLayout_5.addWidget(self.txtdescripcion)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.btnAgregar = QtWidgets.QPushButton(self.fmAgregar)
        self.btnAgregar.setMinimumSize(QtCore.QSize(70, 50))
        self.btnAgregar.setMaximumSize(QtCore.QSize(70, 50))
        self.btnAgregar.setObjectName("btnAgregar")
        self.horizontalLayout.addWidget(self.btnAgregar)
        self.gridLayout.addWidget(self.fmAgregar, 0, 0, 1, 1)
        listaPrecios.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(listaPrecios)
        self.statusbar.setObjectName("statusbar")
        listaPrecios.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(listaPrecios)
        self.toolBar.setEnabled(True)
        self.toolBar.setAcceptDrops(False)
        self.toolBar.setWindowTitle("")
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setAutoFillBackground(False)
        self.toolBar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(QtCore.Qt.NoToolBarArea)
        self.toolBar.setIconSize(QtCore.QSize(24, 24))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        listaPrecios.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actNuevo = QtWidgets.QAction(listaPrecios)
        self.actNuevo.setCheckable(False)
        self.actNuevo.setEnabled(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Application Icons/freeicons24x24/new document.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actNuevo.setIcon(icon)
        self.actNuevo.setIconVisibleInMenu(True)
        self.actNuevo.setObjectName("actNuevo")
        self.actGuardar = QtWidgets.QAction(listaPrecios)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Application Icons/freeicons24x24/save.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actGuardar.setIcon(icon1)
        self.actGuardar.setObjectName("actGuardar")
        self.actModificar = QtWidgets.QAction(listaPrecios)
        self.actModificar.setCheckable(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Application Icons/freeicons24x24/modify.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actModificar.setIcon(icon2)
        self.actModificar.setObjectName("actModificar")
        self.actEliminar = QtWidgets.QAction(listaPrecios)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Application Icons/freeicons24x24/delete.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actEliminar.setIcon(icon3)
        self.actEliminar.setObjectName("actEliminar")
        self.actBuscar = QtWidgets.QAction(listaPrecios)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Application Icons/freeicons24x24/search.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actBuscar.setIcon(icon4)
        self.actBuscar.setObjectName("actBuscar")
        self.actImprimir = QtWidgets.QAction(listaPrecios)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Application Icons/freeicons24x24/print.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actImprimir.setIcon(icon5)
        self.actImprimir.setObjectName("actImprimir")
        self.actSalir = QtWidgets.QAction(listaPrecios)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Application Icons/freeicons24x24/exit.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actSalir.setIcon(icon6)
        self.actSalir.setObjectName("actSalir")
        self.toolBar.addAction(self.actNuevo)
        self.toolBar.addAction(self.actGuardar)
        self.toolBar.addAction(self.actModificar)
        self.toolBar.addAction(self.actEliminar)
        self.toolBar.addAction(self.actBuscar)
        self.toolBar.addAction(self.actImprimir)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actSalir)
        self.lblarticulo.setBuddy(self.fmAgregar)
        self.lblstock.setBuddy(self.sbstock)

        self.retranslateUi(listaPrecios)
        self.actSalir.triggered.connect(listaPrecios.close)
        self.actNuevo.triggered.connect(listaPrecios.nuevo)
        self.actGuardar.triggered.connect(listaPrecios.guardar)
        self.actModificar.triggered.connect(listaPrecios.modificar)
        self.actEliminar.triggered.connect(listaPrecios.eliminar)
        self.actBuscar.triggered.connect(listaPrecios.buscar)
        self.btnAgregar.clicked.connect(listaPrecios.agregar)
        QtCore.QMetaObject.connectSlotsByName(listaPrecios)

    def retranslateUi(self, listaPrecios):
        _translate = QtCore.QCoreApplication.translate
        listaPrecios.setWindowTitle(_translate("listaPrecios", "Lista de Prcios"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("listaPrecios", "Codigo"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("listaPrecios", "Rubro"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("listaPrecios", "Articulo"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("listaPrecios", "Stock"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("listaPrecios", "Precio"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("listaPrecios", "Descripción"))
        self.lblrubro.setText(_translate("listaPrecios", "Rubro"))
        self.lblarticulo.setText(_translate("listaPrecios", "Articulo"))
        self.lblstock.setText(_translate("listaPrecios", "Stock"))
        self.lblprecio.setText(_translate("listaPrecios", "Precio"))
        self.lbdescripcion.setText(_translate("listaPrecios", "Descripcion"))
        self.btnAgregar.setText(_translate("listaPrecios", "Agregar"))
        self.actNuevo.setText(_translate("listaPrecios", "Nuevo"))
        self.actNuevo.setStatusTip(_translate("listaPrecios", "Agregar Nuevo Articulo"))
        self.actGuardar.setText(_translate("listaPrecios", "Guardar"))
        self.actGuardar.setStatusTip(_translate("listaPrecios", "Guardar todos los Articulos"))
        self.actModificar.setText(_translate("listaPrecios", "Modificar"))
        self.actModificar.setStatusTip(_translate("listaPrecios", "Modifica Articulo Seleccionado"))
        self.actEliminar.setText(_translate("listaPrecios", "Eliminar"))
        self.actEliminar.setStatusTip(_translate("listaPrecios", "Elimina Articulo Seleccionado"))
        self.actBuscar.setText(_translate("listaPrecios", "Buscar"))
        self.actBuscar.setStatusTip(_translate("listaPrecios", "Buscar Articulo "))
        self.actImprimir.setText(_translate("listaPrecios", "Imprimir"))
        self.actImprimir.setStatusTip(_translate("listaPrecios", "Imprimir Lista"))
        self.actSalir.setText(_translate("listaPrecios", "Salir"))
        self.actSalir.setStatusTip(_translate("listaPrecios", "Salir de Lista Precios"))

from . import iconosQ
