# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddModCtacte.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_agrmodCtaCte(object):
    def setupUi(self, agrmodCtaCte):
        agrmodCtaCte.setObjectName("agrmodCtaCte")
        agrmodCtaCte.resize(643, 463)
        agrmodCtaCte.setMinimumSize(QtCore.QSize(643, 463))
        agrmodCtaCte.setMaximumSize(QtCore.QSize(643, 463))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconos/freeicons24x24/alien.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        agrmodCtaCte.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(agrmodCtaCte)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 641, 461))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 621, 401))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lblNombre = QtWidgets.QLabel(self.layoutWidget)
        self.lblNombre.setAlignment(QtCore.Qt.AlignCenter)
        self.lblNombre.setObjectName("lblNombre")
        self.gridLayout.addWidget(self.lblNombre, 1, 0, 1, 1)
        self.txtCuit = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtCuit.setObjectName("txtCuit")
        self.gridLayout.addWidget(self.txtCuit, 4, 4, 1, 3)
        self.txtNombre = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtNombre.setObjectName("txtNombre")
        self.gridLayout.addWidget(self.txtNombre, 1, 1, 1, 6)
        self.lblCodpos = QtWidgets.QLabel(self.layoutWidget)
        self.lblCodpos.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCodpos.setObjectName("lblCodpos")
        self.gridLayout.addWidget(self.lblCodpos, 4, 0, 1, 1)
        self.cboLocalidad = QtWidgets.QComboBox(self.layoutWidget)
        self.cboLocalidad.setMinimumSize(QtCore.QSize(150, 0))
        self.cboLocalidad.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cboLocalidad.setObjectName("cboLocalidad")
        self.gridLayout.addWidget(self.cboLocalidad, 3, 4, 1, 3)
        self.cboProvincia = QtWidgets.QComboBox(self.layoutWidget)
        self.cboProvincia.setMinimumSize(QtCore.QSize(130, 0))
        self.cboProvincia.setMaximumSize(QtCore.QSize(130, 16777215))
        self.cboProvincia.setObjectName("cboProvincia")
        self.gridLayout.addWidget(self.cboProvincia, 3, 1, 1, 2)
        self.lblLocalidad = QtWidgets.QLabel(self.layoutWidget)
        self.lblLocalidad.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLocalidad.setObjectName("lblLocalidad")
        self.gridLayout.addWidget(self.lblLocalidad, 3, 3, 1, 1)
        self.cboIvatipo = QtWidgets.QComboBox(self.layoutWidget)
        self.cboIvatipo.setObjectName("cboIvatipo")
        self.cboIvatipo.addItem("")
        self.cboIvatipo.addItem("")
        self.cboIvatipo.addItem("")
        self.cboIvatipo.addItem("")
        self.gridLayout.addWidget(self.cboIvatipo, 5, 1, 1, 2)
        self.lblAlta = QtWidgets.QLabel(self.layoutWidget)
        self.lblAlta.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAlta.setObjectName("lblAlta")
        self.gridLayout.addWidget(self.lblAlta, 0, 4, 1, 2)
        self.dteAlta = QtWidgets.QDateEdit(self.layoutWidget)
        self.dteAlta.setEnabled(False)
        self.dteAlta.setFrame(False)
        self.dteAlta.setAlignment(QtCore.Qt.AlignCenter)
        self.dteAlta.setReadOnly(False)
        self.dteAlta.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dteAlta.setKeyboardTracking(True)
        self.dteAlta.setDateTime(QtCore.QDateTime(QtCore.QDate(2014, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dteAlta.setCalendarPopup(False)
        self.dteAlta.setObjectName("dteAlta")
        self.gridLayout.addWidget(self.dteAlta, 0, 6, 1, 1)
        self.lblProvincia = QtWidgets.QLabel(self.layoutWidget)
        self.lblProvincia.setAlignment(QtCore.Qt.AlignCenter)
        self.lblProvincia.setObjectName("lblProvincia")
        self.gridLayout.addWidget(self.lblProvincia, 3, 0, 1, 1)
        self.lblCuit = QtWidgets.QLabel(self.layoutWidget)
        self.lblCuit.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCuit.setObjectName("lblCuit")
        self.gridLayout.addWidget(self.lblCuit, 4, 3, 1, 1)
        self.txtTelefono = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtTelefono.setMinimumSize(QtCore.QSize(150, 0))
        self.txtTelefono.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txtTelefono.setObjectName("txtTelefono")
        self.gridLayout.addWidget(self.txtTelefono, 5, 4, 1, 3)
        self.lblTelefono = QtWidgets.QLabel(self.layoutWidget)
        self.lblTelefono.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTelefono.setObjectName("lblTelefono")
        self.gridLayout.addWidget(self.lblTelefono, 5, 3, 1, 1)
        self.lblIvatipo = QtWidgets.QLabel(self.layoutWidget)
        self.lblIvatipo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblIvatipo.setObjectName("lblIvatipo")
        self.gridLayout.addWidget(self.lblIvatipo, 5, 0, 1, 1)
        self.lblObs = QtWidgets.QLabel(self.layoutWidget)
        self.lblObs.setAlignment(QtCore.Qt.AlignCenter)
        self.lblObs.setObjectName("lblObs")
        self.gridLayout.addWidget(self.lblObs, 6, 0, 1, 2)
        self.txtObs = QtWidgets.QTextEdit(self.layoutWidget)
        self.txtObs.setObjectName("txtObs")
        self.gridLayout.addWidget(self.txtObs, 6, 2, 1, 5)
        self.txtCodpost = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtCodpost.setMinimumSize(QtCore.QSize(100, 0))
        self.txtCodpost.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txtCodpost.setObjectName("txtCodpost")
        self.gridLayout.addWidget(self.txtCodpost, 4, 1, 1, 1)
        self.lblCodigo = QtWidgets.QLabel(self.layoutWidget)
        self.lblCodigo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCodigo.setObjectName("lblCodigo")
        self.gridLayout.addWidget(self.lblCodigo, 0, 0, 1, 1)
        self.txtCodigo = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtCodigo.setEnabled(False)
        self.txtCodigo.setMinimumSize(QtCore.QSize(100, 0))
        self.txtCodigo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txtCodigo.setObjectName("txtCodigo")
        self.gridLayout.addWidget(self.txtCodigo, 0, 1, 1, 1)
        self.lblDomicilio = QtWidgets.QLabel(self.layoutWidget)
        self.lblDomicilio.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDomicilio.setObjectName("lblDomicilio")
        self.gridLayout.addWidget(self.lblDomicilio, 2, 0, 1, 1)
        self.txtDomicilio = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtDomicilio.setObjectName("txtDomicilio")
        self.gridLayout.addWidget(self.txtDomicilio, 2, 1, 1, 6)
        self.btnAceptar = QtWidgets.QDialogButtonBox(self.groupBox)
        self.btnAceptar.setGeometry(QtCore.QRect(430, 430, 204, 26))
        self.btnAceptar.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.btnAceptar.setObjectName("btnAceptar")

        self.retranslateUi(agrmodCtaCte)
        self.btnAceptar.accepted.connect(agrmodCtaCte.accept)
        self.btnAceptar.rejected.connect(agrmodCtaCte.reject)
        self.cboProvincia.currentIndexChanged['int'].connect(self.cboLocalidad.setFocus)
        self.txtCuit.editingFinished.connect(agrmodCtaCte.validar_cuit)
        QtCore.QMetaObject.connectSlotsByName(agrmodCtaCte)
        agrmodCtaCte.setTabOrder(self.txtCodigo, self.dteAlta)
        agrmodCtaCte.setTabOrder(self.dteAlta, self.txtNombre)
        agrmodCtaCte.setTabOrder(self.txtNombre, self.txtDomicilio)
        agrmodCtaCte.setTabOrder(self.txtDomicilio, self.cboProvincia)
        agrmodCtaCte.setTabOrder(self.cboProvincia, self.cboLocalidad)
        agrmodCtaCte.setTabOrder(self.cboLocalidad, self.txtCodpost)
        agrmodCtaCte.setTabOrder(self.txtCodpost, self.txtCuit)
        agrmodCtaCte.setTabOrder(self.txtCuit, self.cboIvatipo)
        agrmodCtaCte.setTabOrder(self.cboIvatipo, self.txtTelefono)
        agrmodCtaCte.setTabOrder(self.txtTelefono, self.txtObs)
        agrmodCtaCte.setTabOrder(self.txtObs, self.btnAceptar)

    def retranslateUi(self, agrmodCtaCte):
        _translate = QtCore.QCoreApplication.translate
        agrmodCtaCte.setWindowTitle(_translate("agrmodCtaCte", "Agregar CtaCte"))
        self.lblNombre.setText(_translate("agrmodCtaCte", "Nombre:"))
        self.lblCodpos.setText(_translate("agrmodCtaCte", "Codigo Postal:"))
        self.lblLocalidad.setText(_translate("agrmodCtaCte", "Localidad:"))
        self.cboIvatipo.setItemText(0, _translate("agrmodCtaCte", "Res. Inscripto"))
        self.cboIvatipo.setItemText(1, _translate("agrmodCtaCte", "Exento"))
        self.cboIvatipo.setItemText(2, _translate("agrmodCtaCte", "Consumidor Final"))
        self.cboIvatipo.setItemText(3, _translate("agrmodCtaCte", "Monotributista"))
        self.lblAlta.setText(_translate("agrmodCtaCte", "Fecha de Alta:"))
        self.dteAlta.setDisplayFormat(_translate("agrmodCtaCte", "dd/MM/yyyy"))
        self.lblProvincia.setText(_translate("agrmodCtaCte", "Provincia:"))
        self.lblCuit.setText(_translate("agrmodCtaCte", "Cuit:"))
        self.lblTelefono.setText(_translate("agrmodCtaCte", "Telefono:"))
        self.lblIvatipo.setText(_translate("agrmodCtaCte", "Iva Tipo:"))
        self.lblObs.setText(_translate("agrmodCtaCte", "Observaciones:"))
        self.lblCodigo.setText(_translate("agrmodCtaCte", "Codigo Cliente:"))
        self.lblDomicilio.setText(_translate("agrmodCtaCte", "Domicilio Fiscal:"))

from . import iconosQ
