# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'infoPasajero.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_infoPasajero(object):
    def setupUi(self, infoPasajero):
        infoPasajero.setObjectName("infoPasajero")
        infoPasajero.setWindowModality(QtCore.Qt.WindowModal)
        infoPasajero.setEnabled(True)
        infoPasajero.resize(1000, 400)
        infoPasajero.setMinimumSize(QtCore.QSize(1000, 400))
        infoPasajero.setMaximumSize(QtCore.QSize(1000, 400))
        infoPasajero.setBaseSize(QtCore.QSize(680, 630))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconos/freeicons24x24/alien.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        infoPasajero.setWindowIcon(icon)
        infoPasajero.setFrameShape(QtWidgets.QFrame.NoFrame)
        infoPasajero.setFrameShadow(QtWidgets.QFrame.Plain)
        self.layoutWidget = QtWidgets.QWidget(infoPasajero)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 851, 381))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(5, 10, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.layoutWidget)
        self.graphicsView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.graphicsView.setFrameShape(QtWidgets.QFrame.Box)
        self.graphicsView.setFrameShadow(QtWidgets.QFrame.Raised)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTdoc = QtWidgets.QLabel(self.layoutWidget)
        self.lblTdoc.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTdoc.setObjectName("lblTdoc")
        self.verticalLayout.addWidget(self.lblTdoc)
        self.lblApellido = QtWidgets.QLabel(self.layoutWidget)
        self.lblApellido.setAlignment(QtCore.Qt.AlignCenter)
        self.lblApellido.setObjectName("lblApellido")
        self.verticalLayout.addWidget(self.lblApellido)
        self.lblDomicilio = QtWidgets.QLabel(self.layoutWidget)
        self.lblDomicilio.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDomicilio.setObjectName("lblDomicilio")
        self.verticalLayout.addWidget(self.lblDomicilio)
        self.lblFn = QtWidgets.QLabel(self.layoutWidget)
        self.lblFn.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFn.setObjectName("lblFn")
        self.verticalLayout.addWidget(self.lblFn)
        self.lblNacinalidad = QtWidgets.QLabel(self.layoutWidget)
        self.lblNacinalidad.setAlignment(QtCore.Qt.AlignCenter)
        self.lblNacinalidad.setObjectName("lblNacinalidad")
        self.verticalLayout.addWidget(self.lblNacinalidad)
        self.lblProvincia = QtWidgets.QLabel(self.layoutWidget)
        self.lblProvincia.setAlignment(QtCore.Qt.AlignCenter)
        self.lblProvincia.setObjectName("lblProvincia")
        self.verticalLayout.addWidget(self.lblProvincia)
        self.lblLocalidad = QtWidgets.QLabel(self.layoutWidget)
        self.lblLocalidad.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLocalidad.setObjectName("lblLocalidad")
        self.verticalLayout.addWidget(self.lblLocalidad)
        self.lblCivil = QtWidgets.QLabel(self.layoutWidget)
        self.lblCivil.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCivil.setObjectName("lblCivil")
        self.verticalLayout.addWidget(self.lblCivil)
        self.lblTelefono = QtWidgets.QLabel(self.layoutWidget)
        self.lblTelefono.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTelefono.setObjectName("lblTelefono")
        self.verticalLayout.addWidget(self.lblTelefono)
        self.lblOcupacion = QtWidgets.QLabel(self.layoutWidget)
        self.lblOcupacion.setAlignment(QtCore.Qt.AlignCenter)
        self.lblOcupacion.setObjectName("lblOcupacion")
        self.verticalLayout.addWidget(self.lblOcupacion)
        self.lblMail = QtWidgets.QLabel(self.layoutWidget)
        self.lblMail.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMail.setObjectName("lblMail")
        self.verticalLayout.addWidget(self.lblMail)
        self.lblObs = QtWidgets.QLabel(self.layoutWidget)
        self.lblObs.setAlignment(QtCore.Qt.AlignCenter)
        self.lblObs.setObjectName("lblObs")
        self.verticalLayout.addWidget(self.lblObs)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl01 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl01.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl01.setObjectName("lbl01")
        self.verticalLayout_2.addWidget(self.lbl01)
        self.lbl02 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl02.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl02.setObjectName("lbl02")
        self.verticalLayout_2.addWidget(self.lbl02)
        self.lbl03 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl03.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl03.setObjectName("lbl03")
        self.verticalLayout_2.addWidget(self.lbl03)
        self.lbl04 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl04.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl04.setObjectName("lbl04")
        self.verticalLayout_2.addWidget(self.lbl04)
        self.lbl05 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl05.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl05.setAutoFillBackground(False)
        self.lbl05.setObjectName("lbl05")
        self.verticalLayout_2.addWidget(self.lbl05)
        self.lbl06 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl06.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl06.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl06.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl06.setObjectName("lbl06")
        self.verticalLayout_2.addWidget(self.lbl06)
        self.lbl07 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl07.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl07.setObjectName("lbl07")
        self.verticalLayout_2.addWidget(self.lbl07)
        self.lbl08 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl08.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl08.setObjectName("lbl08")
        self.verticalLayout_2.addWidget(self.lbl08)
        self.lbl09 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl09.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl09.setObjectName("lbl09")
        self.verticalLayout_2.addWidget(self.lbl09)
        self.lbl10 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl10.setObjectName("lbl10")
        self.verticalLayout_2.addWidget(self.lbl10)
        self.lbl11 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl11.setObjectName("lbl11")
        self.verticalLayout_2.addWidget(self.lbl11)
        self.lbl12 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl12.setObjectName("lbl12")
        self.verticalLayout_2.addWidget(self.lbl12)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(infoPasajero)
        QtCore.QMetaObject.connectSlotsByName(infoPasajero)

    def retranslateUi(self, infoPasajero):
        _translate = QtCore.QCoreApplication.translate
        self.lblTdoc.setText(_translate("infoPasajero", "Tipo y Numero de Documento:"))
        self.lblApellido.setText(_translate("infoPasajero", "Apellido y Nombre:"))
        self.lblDomicilio.setText(_translate("infoPasajero", "Domicilio:"))
        self.lblFn.setText(_translate("infoPasajero", "Fecha de Nacimiento:"))
        self.lblNacinalidad.setText(_translate("infoPasajero", "Nacionalidad:"))
        self.lblProvincia.setText(_translate("infoPasajero", "Provincia:"))
        self.lblLocalidad.setText(_translate("infoPasajero", "Localidad:"))
        self.lblCivil.setText(_translate("infoPasajero", "Estado Civil:"))
        self.lblTelefono.setText(_translate("infoPasajero", "Telefono:"))
        self.lblOcupacion.setText(_translate("infoPasajero", "Ocupacion:"))
        self.lblMail.setText(_translate("infoPasajero", "Mail:"))
        self.lblObs.setText(_translate("infoPasajero", "Observaciones:"))
        self.lbl01.setText(_translate("infoPasajero", "TextLabel"))
        self.lbl02.setText(_translate("infoPasajero", "TextLabel"))
        self.lbl03.setText(_translate("infoPasajero", "TextLabel"))
        self.lbl04.setText(_translate("infoPasajero", "TextLabel"))
        self.lbl05.setText(_translate("infoPasajero", "TextLabel"))
        self.lbl06.setText(_translate("infoPasajero", "TextLabel"))
        self.lbl07.setText(_translate("infoPasajero", "TextLabel"))
        self.lbl08.setText(_translate("infoPasajero", "TextLabel"))
        self.lbl09.setText(_translate("infoPasajero", "TextLabel"))
        self.lbl10.setText(_translate("infoPasajero", "TextLabel"))
        self.lbl11.setText(_translate("infoPasajero", "TextLabel"))
        self.lbl12.setText(_translate("infoPasajero", "TextLabel"))

from . import iconosQ
