# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HotelPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Hotel(object):
    def setupUi(self, Hotel):
        Hotel.setObjectName("Hotel")
        Hotel.resize(812, 611)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconos/freeicons24x24/alien.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Hotel.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Hotel)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tblHotel = QtWidgets.QTableWidget(self.centralwidget)
        self.tblHotel.setEnabled(True)
        self.tblHotel.setAutoFillBackground(False)
        self.tblHotel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tblHotel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tblHotel.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblHotel.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tblHotel.setAutoScroll(True)
        self.tblHotel.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblHotel.setProperty("showDropIndicator", True)
        self.tblHotel.setDragDropOverwriteMode(False)
        self.tblHotel.setAlternatingRowColors(False)
        self.tblHotel.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblHotel.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblHotel.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tblHotel.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tblHotel.setShowGrid(True)
        self.tblHotel.setGridStyle(QtCore.Qt.NoPen)
        self.tblHotel.setCornerButtonEnabled(False)
        self.tblHotel.setRowCount(19)
        self.tblHotel.setObjectName("tblHotel")
        self.tblHotel.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        item.setText("1")
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tblHotel.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblHotel.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblHotel.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblHotel.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblHotel.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblHotel.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblHotel.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblHotel.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblHotel.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblHotel.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblHotel.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblHotel.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblHotel.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblHotel.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblHotel.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblHotel.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblHotel.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblHotel.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblHotel.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblHotel.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblHotel.setHorizontalHeaderItem(5, item)
        self.tblHotel.horizontalHeader().setVisible(True)
        self.tblHotel.horizontalHeader().setCascadingSectionResizes(False)
        self.tblHotel.horizontalHeader().setHighlightSections(True)
        self.tblHotel.horizontalHeader().setSortIndicatorShown(False)
        self.tblHotel.horizontalHeader().setStretchLastSection(True)
        self.tblHotel.verticalHeader().setVisible(True)
        self.tblHotel.verticalHeader().setDefaultSectionSize(29)
        self.tblHotel.verticalHeader().setSortIndicatorShown(False)
        self.tblHotel.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tblHotel, 0, 0, 1, 1)
        Hotel.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Hotel)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 30))
        self.menubar.setObjectName("menubar")
        self.mnuArchivo = QtWidgets.QMenu(self.menubar)
        self.mnuArchivo.setObjectName("mnuArchivo")
        self.mnuAdministracion = QtWidgets.QMenu(self.menubar)
        self.mnuAdministracion.setObjectName("mnuAdministracion")
        self.mnuFacturacion = QtWidgets.QMenu(self.menubar)
        self.mnuFacturacion.setObjectName("mnuFacturacion")
        self.menuRemito = QtWidgets.QMenu(self.mnuFacturacion)
        self.menuRemito.setObjectName("menuRemito")
        self.menuNota_de_Credito = QtWidgets.QMenu(self.mnuFacturacion)
        self.menuNota_de_Credito.setObjectName("menuNota_de_Credito")
        self.menuFactura = QtWidgets.QMenu(self.mnuFacturacion)
        self.menuFactura.setObjectName("menuFactura")
        self.mnuCtaCte = QtWidgets.QMenu(self.menubar)
        self.mnuCtaCte.setObjectName("mnuCtaCte")
        self.mnuPasajeros = QtWidgets.QMenu(self.menubar)
        self.mnuPasajeros.setObjectName("mnuPasajeros")
        self.mnuModificar = QtWidgets.QMenu(self.mnuPasajeros)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/toolbar/Toolbar(24x24)/Modify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuModificar.setIcon(icon1)
        self.mnuModificar.setObjectName("mnuModificar")
        self.mnuAyuda = QtWidgets.QMenu(self.menubar)
        self.mnuAyuda.setObjectName("mnuAyuda")
        Hotel.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Hotel)
        self.statusbar.setObjectName("statusbar")
        Hotel.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(Hotel)
        self.toolBar.setObjectName("toolBar")
        Hotel.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actCbiarUsr = QtWidgets.QAction(Hotel)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/iconos/freeicons24x24/person.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actCbiarUsr.setIcon(icon2)
        self.actCbiarUsr.setObjectName("actCbiarUsr")
        self.actEgresar = QtWidgets.QAction(Hotel)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/iconos/freeicons24x24/remove.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actEgresar.setIcon(icon3)
        self.actEgresar.setObjectName("actEgresar")
        self.actEstado = QtWidgets.QAction(Hotel)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/iconos/freeicons24x24/find.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actEstado.setIcon(icon4)
        self.actEstado.setObjectName("actEstado")
        self.actAgregar = QtWidgets.QAction(Hotel)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/iconos/freeicons24x24/people.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actAgregar.setIcon(icon5)
        self.actAgregar.setObjectName("actAgregar")
        self.actConsultar = QtWidgets.QAction(Hotel)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/iconos/freeicons24x24/search.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actConsultar.setIcon(icon6)
        self.actConsultar.setObjectName("actConsultar")
        self.actSalir = QtWidgets.QAction(Hotel)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/iconos/freeicons24x24/exit.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actSalir.setIcon(icon7)
        self.actSalir.setObjectName("actSalir")
        self.actXid = QtWidgets.QAction(Hotel)
        self.actXid.setObjectName("actXid")
        self.actXnya = QtWidgets.QAction(Hotel)
        self.actXnya.setObjectName("actXnya")
        self.actIngresar = QtWidgets.QAction(Hotel)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/iconos/freeicons24x24/add.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actIngresar.setIcon(icon8)
        self.actIngresar.setObjectName("actIngresar")
        self.actAgrCtaCte = QtWidgets.QAction(Hotel)
        self.actAgrCtaCte.setIcon(icon8)
        self.actAgrCtaCte.setObjectName("actAgrCtaCte")
        self.actEditCtaCte = QtWidgets.QAction(Hotel)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/iconos/freeicons24x24/modify.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actEditCtaCte.setIcon(icon9)
        self.actEditCtaCte.setObjectName("actEditCtaCte")
        self.actElimCtaCte = QtWidgets.QAction(Hotel)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/iconos/freeicons24x24/erase.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actElimCtaCte.setIcon(icon10)
        self.actElimCtaCte.setObjectName("actElimCtaCte")
        self.actLPasajeros = QtWidgets.QAction(Hotel)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/iconos/freeicons24x24/list.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actLPasajeros.setIcon(icon11)
        self.actLPasajeros.setObjectName("actLPasajeros")
        self.actLCtaCte = QtWidgets.QAction(Hotel)
        self.actLCtaCte.setIcon(icon11)
        self.actLCtaCte.setObjectName("actLCtaCte")
        self.actionEmitir = QtWidgets.QAction(Hotel)
        self.actionEmitir.setObjectName("actionEmitir")
        self.actionConsultar = QtWidgets.QAction(Hotel)
        self.actionConsultar.setObjectName("actionConsultar")
        self.actionAnular_Eliminar = QtWidgets.QAction(Hotel)
        self.actionAnular_Eliminar.setObjectName("actionAnular_Eliminar")
        self.actLPrecios = QtWidgets.QAction(Hotel)
        self.actLPrecios.setIcon(icon11)
        self.actLPrecios.setObjectName("actLPrecios")
        self.actionCrear = QtWidgets.QAction(Hotel)
        self.actionCrear.setObjectName("actionCrear")
        self.actionConsultar_2 = QtWidgets.QAction(Hotel)
        self.actionConsultar_2.setObjectName("actionConsultar_2")
        self.actionAnular_Eliminar_2 = QtWidgets.QAction(Hotel)
        self.actionAnular_Eliminar_2.setObjectName("actionAnular_Eliminar_2")
        self.actionCrear_2 = QtWidgets.QAction(Hotel)
        self.actionCrear_2.setObjectName("actionCrear_2")
        self.actionConsultar_3 = QtWidgets.QAction(Hotel)
        self.actionConsultar_3.setObjectName("actionConsultar_3")
        self.actionAnular_Eliminar_3 = QtWidgets.QAction(Hotel)
        self.actionAnular_Eliminar_3.setObjectName("actionAnular_Eliminar_3")
        self.mnuArchivo.addSeparator()
        self.mnuArchivo.addAction(self.actCbiarUsr)
        self.mnuArchivo.addSeparator()
        self.mnuArchivo.addAction(self.actSalir)
        self.mnuAdministracion.addAction(self.actLPasajeros)
        self.mnuAdministracion.addAction(self.actLCtaCte)
        self.mnuAdministracion.addSeparator()
        self.mnuAdministracion.addAction(self.actLPrecios)
        self.menuRemito.addAction(self.actionCrear)
        self.menuRemito.addAction(self.actionConsultar_2)
        self.menuRemito.addAction(self.actionAnular_Eliminar_2)
        self.menuNota_de_Credito.addAction(self.actionCrear_2)
        self.menuNota_de_Credito.addAction(self.actionConsultar_3)
        self.menuNota_de_Credito.addAction(self.actionAnular_Eliminar_3)
        self.menuFactura.addAction(self.actionEmitir)
        self.menuFactura.addAction(self.actionConsultar)
        self.menuFactura.addAction(self.actionAnular_Eliminar)
        self.mnuFacturacion.addAction(self.menuFactura.menuAction())
        self.mnuFacturacion.addAction(self.menuRemito.menuAction())
        self.mnuFacturacion.addAction(self.menuNota_de_Credito.menuAction())
        self.mnuCtaCte.addSeparator()
        self.mnuCtaCte.addAction(self.actAgrCtaCte)
        self.mnuCtaCte.addAction(self.actEditCtaCte)
        self.mnuCtaCte.addAction(self.actElimCtaCte)
        self.mnuModificar.addAction(self.actXid)
        self.mnuModificar.addAction(self.actXnya)
        self.mnuPasajeros.addAction(self.actIngresar)
        self.mnuPasajeros.addAction(self.actEgresar)
        self.mnuPasajeros.addAction(self.actEstado)
        self.mnuPasajeros.addSeparator()
        self.mnuPasajeros.addAction(self.actAgregar)
        self.mnuPasajeros.addAction(self.actConsultar)
        self.mnuPasajeros.addAction(self.mnuModificar.menuAction())
        self.menubar.addAction(self.mnuArchivo.menuAction())
        self.menubar.addAction(self.mnuAdministracion.menuAction())
        self.menubar.addAction(self.mnuFacturacion.menuAction())
        self.menubar.addAction(self.mnuCtaCte.menuAction())
        self.menubar.addAction(self.mnuPasajeros.menuAction())
        self.menubar.addAction(self.mnuAyuda.menuAction())
        self.toolBar.addAction(self.actIngresar)
        self.toolBar.addAction(self.actAgregar)
        self.toolBar.addSeparator()

        self.retranslateUi(Hotel)
        self.actAgregar.triggered.connect(Hotel.agrPasajero)
        self.actXid.triggered.connect(Hotel.modXid)
        self.actConsultar.triggered.connect(Hotel.consultar)
        self.actXnya.triggered.connect(Hotel.modXnya)
        self.actIngresar.triggered.connect(Hotel.ingresar)
        self.actEgresar.triggered.connect(Hotel.egresar)
        self.actAgrCtaCte.triggered.connect(Hotel.agrCtaCte)
        self.actEditCtaCte.triggered.connect(Hotel.modCtaCte)
        self.actElimCtaCte.triggered.connect(Hotel.elimCtaCte)
        self.actLPasajeros.triggered.connect(Hotel.listaPasajeros)
        self.actLCtaCte.triggered.connect(Hotel.listaCtaCte)
        self.actLPrecios.triggered.connect(Hotel.listaPrecios)
        QtCore.QMetaObject.connectSlotsByName(Hotel)

    def retranslateUi(self, Hotel):
        _translate = QtCore.QCoreApplication.translate
        Hotel.setWindowTitle(_translate("Hotel", "Hotel Bates"))
        self.tblHotel.setSortingEnabled(False)
        item = self.tblHotel.verticalHeaderItem(1)
        item.setText(_translate("Hotel", "2"))
        item = self.tblHotel.verticalHeaderItem(2)
        item.setText(_translate("Hotel", "3"))
        item = self.tblHotel.verticalHeaderItem(3)
        item.setText(_translate("Hotel", "4"))
        item = self.tblHotel.verticalHeaderItem(4)
        item.setText(_translate("Hotel", "5"))
        item = self.tblHotel.verticalHeaderItem(5)
        item.setText(_translate("Hotel", "6"))
        item = self.tblHotel.verticalHeaderItem(6)
        item.setText(_translate("Hotel", "7"))
        item = self.tblHotel.verticalHeaderItem(7)
        item.setText(_translate("Hotel", "8"))
        item = self.tblHotel.verticalHeaderItem(8)
        item.setText(_translate("Hotel", "9"))
        item = self.tblHotel.verticalHeaderItem(9)
        item.setText(_translate("Hotel", "10"))
        item = self.tblHotel.verticalHeaderItem(10)
        item.setText(_translate("Hotel", "11"))
        item = self.tblHotel.verticalHeaderItem(11)
        item.setText(_translate("Hotel", "12"))
        item = self.tblHotel.verticalHeaderItem(12)
        item.setText(_translate("Hotel", "13"))
        item = self.tblHotel.verticalHeaderItem(13)
        item.setText(_translate("Hotel", "15"))
        item = self.tblHotel.verticalHeaderItem(14)
        item.setText(_translate("Hotel", "16"))
        item = self.tblHotel.horizontalHeaderItem(0)
        item.setText(_translate("Hotel", "Codigo"))
        item = self.tblHotel.horizontalHeaderItem(1)
        item.setText(_translate("Hotel", "Fecha Ingreso"))
        item = self.tblHotel.horizontalHeaderItem(2)
        item.setText(_translate("Hotel", "Hora"))
        item = self.tblHotel.horizontalHeaderItem(3)
        item.setText(_translate("Hotel", "Fecha Egreso"))
        item = self.tblHotel.horizontalHeaderItem(4)
        item.setText(_translate("Hotel", "Hora"))
        item = self.tblHotel.horizontalHeaderItem(5)
        item.setText(_translate("Hotel", "Nombre y Apellido"))
        self.mnuArchivo.setTitle(_translate("Hotel", "Archivo"))
        self.mnuAdministracion.setTitle(_translate("Hotel", "A&dministración"))
        self.mnuFacturacion.setTitle(_translate("Hotel", "Fact&uración"))
        self.menuRemito.setTitle(_translate("Hotel", "&Remito"))
        self.menuNota_de_Credito.setTitle(_translate("Hotel", "&Nota de Credito"))
        self.menuFactura.setTitle(_translate("Hotel", "&Factura"))
        self.mnuCtaCte.setTitle(_translate("Hotel", "&Cuentas Corrientes"))
        self.mnuPasajeros.setTitle(_translate("Hotel", "Pasa&jeros"))
        self.mnuModificar.setTitle(_translate("Hotel", "&Modificar"))
        self.mnuAyuda.setTitle(_translate("Hotel", "A&yuda"))
        self.toolBar.setWindowTitle(_translate("Hotel", "toolBar"))
        self.actCbiarUsr.setText(_translate("Hotel", "&Cambiar Usuario"))
        self.actEgresar.setText(_translate("Hotel", "&Egresar"))
        self.actEstado.setText(_translate("Hotel", "Esta&do"))
        self.actAgregar.setText(_translate("Hotel", "&Agregar"))
        self.actConsultar.setText(_translate("Hotel", "&Consultar"))
        self.actSalir.setText(_translate("Hotel", "&Salir"))
        self.actXid.setText(_translate("Hotel", "&Por ID"))
        self.actXnya.setText(_translate("Hotel", "Por Apellido &y Nombre"))
        self.actIngresar.setText(_translate("Hotel", "&Ingresar"))
        self.actAgrCtaCte.setText(_translate("Hotel", "&Agregar"))
        self.actEditCtaCte.setText(_translate("Hotel", "&Modificar"))
        self.actElimCtaCte.setText(_translate("Hotel", "&Borrar"))
        self.actLPasajeros.setText(_translate("Hotel", "&Lista de Pasajeros"))
        self.actLCtaCte.setText(_translate("Hotel", "Lista &de Cuentas Corrientes"))
        self.actionEmitir.setText(_translate("Hotel", "&Crear"))
        self.actionConsultar.setText(_translate("Hotel", "C&onsultar"))
        self.actionAnular_Eliminar.setText(_translate("Hotel", "&Anular/Eliminar"))
        self.actLPrecios.setText(_translate("Hotel", "Lista de &Precios"))
        self.actionCrear.setText(_translate("Hotel", "&Crear"))
        self.actionConsultar_2.setText(_translate("Hotel", "C&onsultar"))
        self.actionAnular_Eliminar_2.setText(_translate("Hotel", "&Anular/Eliminar"))
        self.actionCrear_2.setText(_translate("Hotel", "&Crear"))
        self.actionConsultar_3.setText(_translate("Hotel", "C&onsultar"))
        self.actionAnular_Eliminar_3.setText(_translate("Hotel", "&Anular/Eliminar"))

from . import iconosQ
